import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "dist",
      "node_modules",
      "playwright-report",
      "test-results",
      "*.tsbuildinfo",
      // Generated by @tanstack/router-plugin.
      "src/routeTree.gen.ts",
      // Deno edge functions — different runtime/globals, not linted here.
      "supabase/functions",
    ],
  },
  {
    files: ["**/*.{ts,tsx}"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs["recommended-latest"].rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      // react-hooks v7 (React-Compiler era) flags synchronous setState in an
      // effect. The current hooks use it for legitimate external-state sync
      // (media-query match, auth session, ratings cache). Keep it visible as a
      // warning; the canonical rewrites are tracked for the Phase 3 refactor.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
  // TanStack route files export a `Route` constant alongside the component by
  // design, so the fast-refresh "components only" rule doesn't apply.
  {
    files: ["src/routes/**/*.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  // Node-context config files.
  {
    files: ["*.config.{js,ts}", "vite.config.ts", "playwright.config.ts"],
    languageOptions: {
      globals: globals.node,
    },
  },
  // Vitest + Playwright test files run in node/jsdom and use test globals.
  {
    files: ["**/*.test.{ts,tsx}", "e2e/**/*.ts", "src/test/**/*.{ts,tsx}"],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
  },
  // Disables ESLint formatting rules that would conflict with Prettier.
  prettier,
);
